// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGE.Infraestructura;

#nullable disable

namespace SGE.Infraestructura.Migrations
{
    [DbContext(typeof(SGEDbContext))]
    partial class SGEDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SGE.Dominio.Expedientes.Expediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioUltimoCambio")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Caratula", "SGE.Dominio.Expedientes.Expediente.Caratula#Caratula", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Caratula");
                        });

                    b.HasKey("Id");

                    b.ToTable("Expedientes");
                });

            modelBuilder.Entity("SGE.Dominio.Tramites.Tramite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Etiqueta")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioUltimoCambio")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Contenido", "SGE.Dominio.Tramites.Tramite.Contenido#ContenidoTramite", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Contenido");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("Tramites");
                });

            modelBuilder.Entity("SGE.Dominio.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsAdministrador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PermisosSerializados")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("Permisos");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CorreoElectronico", "SGE.Dominio.Usuarios.Usuario.CorreoElectronico#CorreoElectronico", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("CorreoElectronico");
                        });

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SGE.Dominio.Tramites.Tramite", b =>
                {
                    b.HasOne("SGE.Dominio.Expedientes.Expediente", null)
                        .WithMany()
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
