// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGE.Infraestructura;

#nullable disable

namespace SGE.Infraestructura.Migrations
{
    [DbContext(typeof(SGEDbContext))]
    partial class SGEDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SGE.Dominio.Expedientes.Expediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioUltimoCambio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Expedientes");
                });

            modelBuilder.Entity("SGE.Dominio.Tramites.Tramite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Etiqueta")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExpedienteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaUltimaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioUltimoCambio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteId");

                    b.ToTable("Tramites");
                });

            modelBuilder.Entity("SGE.Dominio.Expedientes.Expediente", b =>
                {
                    b.OwnsOne("SGE.Dominio.Comun.Caratula", "Caratula", b1 =>
                        {
                            b1.Property<Guid>("ExpedienteId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ExpedienteId");

                            b1.ToTable("Expedientes");

                            b1.WithOwner()
                                .HasForeignKey("ExpedienteId");
                        });

                    b.Navigation("Caratula")
                        .IsRequired();
                });

            modelBuilder.Entity("SGE.Dominio.Tramites.Tramite", b =>
                {
                    b.HasOne("SGE.Dominio.Expedientes.Expediente", null)
                        .WithMany()
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SGE.Dominio.Comun.ContenidoTramite", "Contenido", b1 =>
                        {
                            b1.Property<Guid>("TramiteId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("TramiteId");

                            b1.ToTable("Tramites");

                            b1.WithOwner()
                                .HasForeignKey("TramiteId");
                        });

                    b.Navigation("Contenido")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
